name: PoopPlugin
version: 1.0
main: me.tauntaunchewie.PoopPlugin
api-version: 1.18

commands:
  poop:
    description: Drops a load when a player hits SHIFT
    usage: /<command> on/off/status
    permission: poopplugin.poop
    permission-message: You do not have permission to execute that command.

permissions:
  poopplugin.seeplugin:
    description: Basic ability to see the plugin
    default: op
  poopplugin.set:
    description: Permission to enable and disable pooping
    default: op